[workspace]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
name = "open_imu_camera_calibrator_ws"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CMAKE_INSTALL_MODE = "SYMLINK"

[tasks]
configure-theia = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DMETIS_LIBRARY=$CONDA_PREFIX/lib/libmetis.so",
  "-DMETIS_INCLUDE_DIR=$CONDA_PREFIX/include",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-S",
  "pyTheiaSfM/",
  "-B",
  "build/pyTheiaSfM/",
] }
build-theia = { cmd = "cmake --build build/pyTheiaSfM/", depends-on = [
  "configure-theia",
] }
install-theia = { cmd = "cmake --install build/pyTheiaSfM --prefix $CONDA_PREFIX", depends-on = [
  "build-theia",
] }
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  # "-DMETIS_LIBRARY=$CONDA_PREFIX/lib/libmetis.so",
  "-DMETIS_INCLUDE_DIR=$CONDA_PREFIX/include",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-S",
  "OpenImuCameraCalibrator/",
  "-B",
  "build/OpenImuCameraCalibrator/",
] }
build = { cmd = "cmake --build build/OpenImuCameraCalibrator/", depends-on = [
  "configure",
] }

[dependencies]
opencv = ">=4.5.0,<4.7"
ceres-solver = ">=2.1.0,<2.2"
lapack = ">=3.9.0,<4"
blas-devel = ">=3.9.0,<4"
cmake = ">=3,<4"
ninja = ">=1.13.0,<2"
# gfortran = ">=15.1.0,<15.2"
pthread-stubs = ">=0.4,<0.5"
gcc_linux-64 = ">=15.1.0,<16"
gxx_linux-64 = ">=15.1.0,<16"
python = ">=3.10,<3.11"
#scipy = "*"

[pypi-dependencies]
opencv-contrib-python = ">=4.5, <4.6"
natsort = "==8.2.0"
scipy = "==1.10.1"
# numpy = ">=1.23,<1.27"
matplotlib = "==3.7.0"
py-gpmf-parser = "==0.0.3"
