[workspace]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
name = "cuda_rrt_ws"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CMAKE_INSTALL_MODE = "SYMLINK"
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"
CUDA_HOME = "$CONDA_PREFIX/targets/x86_64-linux"

[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld",
  "-DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld",
  "-DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld",
  "-S",
  "pRRTC/",
  "-B",
  "build/",
] }
build = { cmd = "cmake --build build/ --config Release", depends-on = [
  "configure",
] }
install = { cmd = "cmake --install build/ --prefix $CONDA_PREFIX", depends-on = [
  "build",
] }


[dependencies]
cuda = "12.4.1"
eigen = ">=3.4.0,<4"
nlohmann_json = ">=3.11.3,<4"
lld = ">=20.1.1,<21"
ninja = ">=1.12.1,<2"
clang = ">=20.1.1,<21"
clangxx = ">=20.1.1,<21"
cuda-nvcc = ">=12.4.131,<13"
