[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ompl_workspace"
platforms = ["linux-64"]
version = "0.1.0"


[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DBUILD_TESTING=ON",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DOMPL_REGISTRATION=OFF",
  "-S",
  "ompl/",
  "-B",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends_on = ["configure"] }

test = { cmd = "ctest --output-on-failure", cwd = "build", depends_on = [
  "build",
] }

[dependencies]
compilers = ">=1.8.0,<2"
cmake = ">=3.31.1,<4"
pkg-config = ">=0.29.2,<0.30"
eigen = ">=3.4.0,<4"
make = ">=4.4.1,<5"
ninja = ">=1.12.1,<2"
libboost-devel = ">=1.86.0,<2"
