[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ompl_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CMAKE_INSTALL_MODE = "SYMLINK"
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DBUILD_TESTING=ON",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DOMPL_REGISTRATION=OFF",
  "-S",
  "ompl/",
  "-B",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends-on = ["configure"] }
install = { cmd = "cmake --install .build/ --prefix $CONDA_PREFIX", depends-on = [
  "build",
] }
test = { cmd = "ctest --output-on-failure", cwd = ".build", depends-on = [
  "build",
] }

build-wheel = { cmd = "python -m build --wheel", cwd = "ompl/py-bindings" }
build-wheels = { cmd = "cibuildwheel py-bindings --platform linux", cwd = "ompl/", env = { CIBW_BUILD = "cp311-manylinux_x86_64", CIBW_BUILD_VERBOSITY = "1" } }

[dependencies]
eigen = ">=3.4.0,<4"
python = "==3.11"
numpy = "==2.2.1"
boost = ">=1.85.0,<2"
libboost-python = ">=1.85.0,<2"
cibuildwheel = ">=2.21.3,<3"

[pypi-dependencies]
pygccxml = ">=2.6.1, <3"
pyplusplus = ">=1.8.5, <2"
ninja = ">=1.11.1.3, <2"
build = ">=1.2.2.post1, <2"
