[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "A workspace for developing mujoco/mujoco_mpc from source"
name = "mujoco_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[target.unix.activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DMUJOCO_SIMULATE_USE_SYSTEM_GLFW=ON",
  "-S",
  "mujoco/",
  "-B",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends_on = ["configure"] }
install = { cmd = "cmake --install .build/", depends_on = ["build"] }

configure-mjpc = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DMJPC_USE_SYSTEM_GLFW=ON",
  "-DMUJOCO_SIMULATE_USE_SYSTEM_GLFW=ON",
  "-S",
  "mujoco_mpc/",
  "-B",
  ".build/mjpc",
] }
build-mjpc = { cmd = "cmake --build .build/mjpc --target mjpc", depends_on = ["configure-mjpc"] }
install-mjpc = { cmd = "cmake --install .build/mjpc", depends_on = ["build-mjpc"] }


[dependencies]
glfw = ">=3.4,<4"

[host-dependencies]
ninja = ">=1.12.1,<2"
cmake = "3.22.*"
xorg-libxcursor = ">=1.2.3,<2"
xorg-libxi = ">=1.8.2,<2"
