[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "A workspace for developing mujoco/mujoco_mpc from source"
name = "mujoco_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
MADRONA_MWGPU_KERNEL_CACHE = "build/kernel_cache"
MADRONA_BVH_KERNEL_CACHE = "build/bvh_cache"

[target.unix.activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DMUJOCO_SIMULATE_USE_SYSTEM_GLFW=ON",
  "-S",
  "mujoco/",
  "-B",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends-on = ["configure"] }
install = { cmd = "cmake --install .build/", depends-on = ["build"] }

configure-mjpc = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DMJPC_USE_SYSTEM_GLFW=ON",
  "-DMUJOCO_SIMULATE_USE_SYSTEM_GLFW=ON",
  "-S",
  "mujoco_mpc/",
  "-B",
  ".build/mjpc",
] }
build-mjpc = { cmd = "cmake --build .build/mjpc --target mjpc", depends-on = [
  "configure-mjpc",
] }
install-mjpc = { cmd = "cmake --install .build/mjpc", depends-on = [
  "build-mjpc",
] }

configure-madrona = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-S",
  "madrona_mjx/",
  "-B",
  "madrona_mjx/build",
] }
build-madrona = { cmd = "cmake --build madrona_mjx/build", depends-on = [
  "configure-madrona",
] }
install-madrona = { cmd = "cmake --install madrona_mjx/build", depends-on = [
  "build-madrona",
] }


[dependencies]
glfw = ">=3.4,<4"
python = ">=3.11,<3.12"
cuda-nvcc = ">=12.4.131,<13"
cuda = "12.4.1"
cudnn = ">=9.8.0.87,<10"
vulkan-tools = ">=1.3.250,<2"

[pypi-dependencies]
playground = { path = "mujoco_playground", editable = true, extras = ["all"] }
mujoco-warp = { path = "mujoco_warp", editable = true }
madrona_mjx = { path = "madrona_mjx", editable = true }
jax = { version = "*", extras = ["cuda12_local"] }

[host-dependencies]
ninja = ">=1.12.1,<2"
cmake = "3.31.*"
xorg-libxcursor = "*"
xorg-libxi = "*"
xorg-libxrandr = "*"
mesalib = "*"
