[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "drake_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
  "-S",
  ".",
  "-B",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends-on = ["configure"] }

# https://github.com/RobotLocomotion/drake/releases
install-drake = """
test -e .drake || mkdir .drake -p &&
wget https://github.com/RobotLocomotion/drake/releases/download/v$DRAKE_VERSION/drake-$DRAKE_VERSION-$(lsb_release --codename --short).tar.gz -O .drake/drake.tar.gz &&
tar xzf .drake/drake.tar.gz --strip-components 1 -C $CONDA_PREFIX
"""

[dependencies]
ninja = ">=1.12.1,<2"
cmake = ">=3.30.5,<4"
lld = ">=19.1.3,<20"
eigen = ">=3.4.0,<4"
fmt = "==8.1.1"       # Same as drake's version
spdlog = "==1.9.2"    # Same as drake's version
gflags = ">=2.2.2,<3"
python = "==3.11"

[activation.env]
DRAKE_VERSION = "1.35.0"
