[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "vamp"
platforms = ["linux-64"]
version = "0.1.0"


[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DBUILD_TESTING=ON",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-S",
  "vamp/",
  "-B",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends_on = ["configure"] }
install = { cmd = "cmake --install .build/", depends_on = ["build"] }

[dependencies]
cmake = ">=3.31.1,<4"
eigen = ">=3.4.0,<4"
make = ">=4.4.1,<5"
ninja = ">=1.12.1,<2"
libboost-devel = ">=1.86.0,<2"
python = "==3.11"
scikit-build-core = ">=0.10.7,<0.11"

[pypi-options]
no-build-isolation = ["vamp"]

[pypi-dependencies]
vamp = { path = "./vamp", editable = true, extras = ["examples", "heightmaps"]}
