[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "behaviortree_py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
bt-configure = "cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S external/BehaviorTree.CPP/ -B .build/behaviortree_cpp"
bt-build = { cmd = "cmake --build .build/behaviortree_cpp", depends_on = ["bt-configure"] }
bt-install = { cmd = "cmake --install .build/behaviortree_cpp --prefix $CONDA_PREFIX", depends_on = ["bt-build"] }
configure = "cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B .build/"
build = { cmd = "cmake --build .build/", depends_on = ["configure"] }

[dependencies]
pybind11 = ">=2.12.0,<2.13"
ninja = ">=1.12.1,<1.13"
cmake = ">=3.29.3,<3.30"
lld = ">=18.1.5,<18.2"
eigen = ">=3.4.0,<3.5"
python = "==3.11"
zeromq = ">=4.3.5,<5"
gtest = ">=1.15.2,<2"
