[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge", "pytorch"]
description = "Add a short description here"
name = "curobo_workspace"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CUROBO_TORCH_CUDA_GRAPH_RESET = "1"
PATH = "$CONDA_PREFIX/nvvm/bin:$PATH"
CUDA_HOME = "$CONDA_PREFIX/targets/x86_64-linux"

[tasks]
jupyter = "jupyter lab --ip=0.0.0.0"
meshcat = "meshcat-server --open"
build-inplace = { cmd = "python setup.py build_ext --inplace", cwd = "external/curobo" }
compdb = { cmd = "ninja -t compdb > ../compile_commands.json", cwd = "external/curobo/build/temp.linux-x86_64-cpython-311" }
curobo-build = { depends-on = ["build-inplace", "compdb"] }

[dependencies]
python = "==3.11"
pytorch = { version = "==2.5.1", channel = "pytorch" }
setuptools = ">=75.5.0,<76"
cuda-nvcc = ">=12.4.131,<13"
matplotlib = ">=3.9.2,<4"
jupyterlab = ">=4.3.1,<5"

[pypi-options]
no-build-isolation = ["nvidia-curobo"]

[pypi-dependencies]
nvidia-curobo = { path = "./external/curobo", editable = true, extras = [] }
meshcat = ">=0.3.2, <0.4"
transforms3d = ">=0.4.2, <0.5"
